### ISSUE TITLE
translation to dutch

### ISSUE THREAD

**Issue by AstridHKU** [disillusionment/COVID-19#1]
Hey there, good job!
Not so experienced with github, but feel free to grab the dutch translations from my drive:
 https://drive.google.com/open?id=1vFpHkPwudllCNUDtV7r7dGXnglwPvxLv
or here's the smaller pdf (but also fine I think? No idea why the others were so big...) 

[Covid19_Protocols_NL.pdf](https://github.com/disillusionment/COVID-19/files/4358838/Covid19_Protocols_NL.pdf)

**Comment by mayhem** [comment]
Thank you. We can close this issue now that I've created the PR to include these files.
